version: "3"

services:
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"

  s3:
    image: rustfs/rustfs:1.0.1
    environment:
      RUSTFS_ACCESS_KEY: ABCDEFGHIJKLMNOQRSTU
      RUSTFS_SECRET_KEY: abcdefghiklmnoqrstuvwxyz1234567890abcdef
    ports:
      - "9000:9000"
