---
version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/astral-sh/uv:python3.11-trixie
      - image: mongo:6.0.4
      - image: minio/minio:RELEASE.2022-07-08T00-05-23Z
        environment:
          MINIO_ACCESS_KEY: ABCDEFGHIJKLMNOQRSTU
          MINIO_SECRET_KEY: abcdefghiklmnoqrstuvwxyz1234567890abcdef
        command: server /export
    environment:
      BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
            - py-cache-v4-{{ arch }}-{{ checksum "pyproject.toml" }}-{{ checksum "uv.lock" }}
            - py-cache-v4-{{ arch }}-{{ checksum "pyproject.toml" }}
            - py-cache-v4-{{ arch }}-{{ .Branch }}
            - py-cache-v4-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install Python dependencies
          command: |
            uv sync --frozen
      - save_cache:
          key: py-cache-v4-{{ arch }}-{{ checksum "pyproject.toml" }}-{{ checksum "uv.lock" }}
          paths:
            - .venv
      - save_cache:
          key: py-cache-v4-{{ arch }}-{{ checksum "pyproject.toml" }}
          paths:
            - .venv
      # TODO: apply ruff
      # - run:
      #     name: Lint and format code
      #     command: |
      #       uv run ruff check .
      #       uv run ruff format --check .
      - run:
          name: Run tests
          command: |
            uv run pytest -ra
      - run:
          name: Build a distributable package
          command: |
            uv build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: ghcr.io/astral-sh/uv:python3.11-trixie
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            uv publish --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/flask_storage-*.whl

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /[0-9]+(\.[0-9]+)+/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
